---
- name: Pull docker image for mariadb
  shell: |
    set -e
    set -x
    docker pull mariadb:10.3
  args:
    executable: /bin/bash

- name: Run mariadb container
  shell: |
    set -e
    set -x
    docker run -d --name buildset_history -e MYSQL_ROOT_PASSWORD=root mariadb:10.3
  args:
    executable: /bin/bash

- name: Copy sqldump with examples
  copy:
    src: zuul.sql
    dest: ~/zuul.sql

- name: Create database for zuul history
  shell: |
    set -e
    set -x
    docker exec -i buildset_history mysql -proot -uroot -e "CREATE DATABASE zuul;"
  args:
    executable: /bin/bash

- name: Import database from zuul.sql dump file
  shell: |
    set -e
    set -x
    docker exec -i buildset_history mysql -proot -uroot zuul < zuul.sql
  args:
    executable: /bin/bash